### ISSUE TITLE
lacking of _caffe

### ISSUE THREAD

**Issue by chensongkui** [Ding-Liu/DeepDenoising#5]
[zhuml@mediaszu exper]$ sh main_test_denoise.sh
Traceback (most recent call last):
  File "tools/deepdenoising.py", line 14, in <module>
    from denoise_image import ImageDenoiser
  File "/home/DeepDenoising-master/DeepDenoising-master/exper/tools/denoise_image.py", line 18, in <module>
    import caffe
  File "/home/DeepDenoising-master/DeepDenoising-master/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/DeepDenoising-master/DeepDenoising-master/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe

Hi, i meet a problem about lacking of a module named _caffe when i run ''sh main_test_denoise.sh'', can you help me?

**Comment by linyangfei** [comment]
You have to run "make all" first
